### ISSUE TITLE
Not working, giving error 401 please help tanvesh01

### ISSUE THREAD

**Issue by yash-me** [tanvesh01/online-ide#15]
<img width="651" alt="Screenshot 2020-11-09 at 7 02 58 PM" src="https://user-images.githubusercontent.com/56098976/98547446-31d36400-22be-11eb-8036-d962c0091388.png">
<img width="1440" alt="Screenshot 2020-11-09 at 7 03 25 PM" src="https://user-images.githubusercontent.com/56098976/98547479-40218000-22be-11eb-8809-22811f9d49d5.png">

**Comment by tanvesh01** [comment]
Hey @yash-me you have to make an account on [Jdoodle](https://www.jdoodle.com/) get your id and secret
then plugin those in `server.js`

**Comment by yash-me** [comment]
Ooo okk okk so that's it right. and can you please tell me Jdoodle is telling 200 credits per day, does it means 200 times I can compile code? Please tell me brother

**Comment by tanvesh01** [comment]
Yes, 200 times in 24 hours, for their free plan.

**Comment by yash-me** [comment]
Great buddy, it's working now thanks soo much for your help.
